UpdateREADME.md
tuanle03/Code_learn_spa pull request #12
Opened 2023-12-10 21:29 UTC by PongZuaa

check for me please

2023-12-11 00:37 UTC, baoipc commented on README.md
- @tuanle03 nên viết tiếng việt không nhỉ
- Thiếu thông tin của tôi với Tuấn

2023-12-11 00:37 UTC, baoipc commented
Ảnh đang bị lỗi hiển thị

2023-12-11 10:08 UTC, tuanle03 requested changes

2023-12-11 10:08 UTC, tuanle03 commented on README.md
Tiếng anh cũng đc, viết ngắn gọn lại chút, sửa lỗi hiển thị nữa

2023-12-13 14:47 UTC, tuanle03 requested changes

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +  ![Article TSX](https://lh3.googleusercontent.com/pw/ABLVV86XOkWETjbsrW9eJ93ROKTwD-yFFZy0qm7vz9-Byx2BUOAYR3fonVJvNgAn-anwmdnP6hwa8bekriS9iZNdMhOAgrchM1NZLWFEN1GZLxGVBRiDnN6hhPc7yA8IAhqjDBikew5KnkTI0
này là gì v?

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +  ![Article CSS](https://lh3.googleusercontent.com/pw/ABLVV875jaxlTUR9XgZz4rTLVUfcYTu0ccshzYFE05NLHVNJ8bcKo-8LRhDcSJLkUyu1Hohq23bOY4voWiuEpmb0SqCw7MpSxJM1GeWX6Ue3MBvuxIOfLZSt78jooiTxH4mH6_n_6UD9ad5Kc
?

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +![Node modules](https://lh3.googleusercontent.com/pw/ABLVV86fF6ZuAQwi7CabJqSCVLABHG-CKa0YY8NqYMjX_PgYRqXx6nIggy1tLC8_r5Dp07SmUpo7SjlSkXIXOxWTVVzyvh1c4Ms5aI1qdBaeI1PWrEDxzMhaxl52Df6E4xD-UCVVRbbkad0HsG
?

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +![Source folder](https://lh3.googleusercontent.com/pw/ABLVV86O1WTEQIeuJFzMbCLOU9eXCdsyBK6lyb8TpeLgJ4zZfdwA2zsvwuDDG88ZyjQP1LsJmdVLqfNUNt6yqC9M40ySoeytDPuBqyIlQ8i2HYa6rXxXzwJqyH4atzXM2UO-wIplufsg289My
?

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +![App Component](https://lh3.googleusercontent.com/pw/ABLVV87btE-mCECOnYbtKR3Bjdve7jEkmX9sk7Yugd9Q79HsclT1DTi-xTQUfWXKVdIoLdjGdIuSMYZ4gZp0nZKS93BTuvKN_scXqIs5rgFqqxGDCmjHRNGBu5pD3Q8XjUIMp__lKnSI8jrTR
?

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +![Web Demo](https://lh3.googleusercontent.com/pw/ABLVV85Z5btspzYhOTSj6z9u5DusVSWujH6_zsvHqcxes_mk1pVyLo76T5X12AEuuGsP13cMxfgM23XqLgrEwXUJh1f3hM8Jw-i7XTlOygCRpvQ4jszX9Z9323MM8M2elAGAwOVonZhMeRPeGzAOds
Nào deploy thì để link vô sau

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +![Web Demo Code](https://lh3.googleusercontent.com/pw/ABLVV86c8TF4VWxBtnFHLKRasW3ufaRNK8hsb2vG1hDYJBmqYt6Zj-Q0GuVN-6GFYxbVrPn_P9GyB_uCQzza_4KfPgRc388QIw7yZ4a1563_iexF5BlUyvK1IJZcFuBdZE9r-1yOAxSG4r3t4
?

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +![Vite](https://lh3.googleusercontent.com/pw/ABLVV84Fz-Hok3dOQ6do5t80AcTlOWDLLMC5KhyI-aq3QPRHV4vSYapIvNxnvJPmzICydohMGyDy38YZqAwAsdtG6-xWoRPrc4j6PLpGrDY9OF6wXEfkbN6Y30cq6BbNG4dnwI727N-m598zU6kG_z6o55
?

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +![Typescript](https://lh3.googleusercontent.com/pw/ABLVV86g295JtD4mttkSbMRLrk_IDtng49lwBtuK7YiD6zDycgetZWJ83ZgZfVeHpScEDxPqc7By5AnaNM7AQeSUl3ZBV1-R5oTC5HCpwjGWuA3q0Cgnq5H33VtO-e4qLtHVQQOqXrrxRTOtyIbH
?

2023-12-13 14:47 UTC, tuanle03 commented on README.md
> +![Package JSON](https://lh3.googleusercontent.com/pw/ABLVV86AVny_M-_GRugzu4dipW8hdDbHg5eIs1M0fZIs0H_2a-1C3BzMQ_gCnPwtD-0VYU716yzuSQ3To5KscC0OkTQ6meCblaq7ctogs3lzaTkM1QBTPd7fZRqQ9UtEqu2O8L35Tx7CzV3uHp
?

2023-12-20 19:26 UTC, tuanle03 approved these changes
LGTM

2023-12-20 19:26 UTC, merged